version: '3.8'
services:
  user-service:
    container_name: user-service
    image: t0ky0le/user-service:1.0
    build:
      context: .
    ports:
      - "8091:8091"
    environment:
      - SERVER_PORT=8091
      - DB_HOST=db_user
      - DB_PORT=8102
      - DB_NAME=db_user
      - DB_USERNAME=luffy
      - DB_PASSWORD=123
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      - db_user

  db_user:
    container_name: db_user
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_user
      POSTGRES_USER: luffy
      POSTGRES_PASSWORD: 123
    ports:
      - "8102:5432"
    expose:
      - 5432
